config.py
main.py
media_platform/xhs/core.py

1. 增加新的登录方式，可以支持在配置文件中配置cookie中的web_session文件，从而保持登录状态。
2. 修复在爬取小红书文章的时候，遇到文章id不存在的时候，由于抛出异常导致程序中断的问题。增加了异常捕获的部分，从而可以程序不中断，继续爬取接下来的文章

handby&catch exception

---

models/douyin.py
models/xiaohongshu.py
requirements.txt

看了一下大佬用的orm库支持Pydantic用法，加了几行代码

orm添加Pydantic数据验证

---

store/xhs/xhs_store_impl.py

修复小红书评论重复插入

---

docs/常见问题.md

原来的“常见问题.md"结尾多了一个 "`" 并且少了”<br>“标签。
这是一个微不足道的修改，但是这是我第一次在GitHub上做contributor ，我是一名大一新生，非常希望得到您的认可。

fix: 修复了“常见问题.md"的语法问题。

---

docs/常见问题.md

很抱歉，之前忘记测试了，
现在这一版本是正确的
您刚刚通过了我的第一个版本，非常感激。

fix ： 修复”常见问题.md“

---

media_platform/douyin/login.py

Remove duplication Qrcode Show

---

media_platform/weibo/core.py

Scripts output "Bilibili crawler finished" when Weibo crawler finished.

chore: fix wrong log output when weibo crawler finished

---

docs/常见问题.md

感觉之前回答过好几次类似的问题, 但是 issue 出现频率还是挺高的.....

chore: 增加常见问题[小红书扫码登录成功后如何手动验证]

---

media_platform/xhs/help.py

fix:兼容网页端上传的图片原图获取

---

media_platform/xhs/help.py

fix: 修复 f-string 双引号问题

---

store/bilibili/bilibili_store_impl.py
store/douyin/douyin_store_impl.py
store/kuaishou/kuaishou_store_impl.py
store/weibo/weibo_store_impl.py
store/xhs/xhs_store_impl.py

新增id，解决同一天内的不同查询写入同一个文件的问题，方便提取新的查询结果。

新增id，解决同一天内的不同查询写入同一个文件的问题

---

config/db_config.py
requirements.txt

1. add more configs, such as host, port
2. use dotenv to load env from .env file
用bili爬虫测试

feat: improve db config

---

cmd_arg/arg.py
config/base_config.py
tools/utils.py

新增 --get_comment, --get_sub_comment, --save_data_option, --cookies command args
打印config值
test with no args， 使用config默认值
and with args, 使用arg值

add few more cmd args 

---

config/base_config.py
media_platform/douyin/core.py
media_platform/douyin/field.py

feat: base_config 增加抖音发布时间配置
fix: 抖音排序类型枚举值
fix: 抖音offset计算问题（page=1时，应该取1-10条数据，offset=0）

feat: base_config 增加抖音发布时间配置

---

README.md
store/xhs/__init__.py

小红书 creator 的 IP 归属地应该取字段 ipLocation

修复无法采集小红书 creator IP 归属信息的问题

---

config/base_config.py

fix: update outdated comment in base_config.py

---

base/base_crawler.py
media_platform/bilibili/core.py
schema/tables.sql
store/bilibili/__init__.py
store/bilibili/bilibili_store_impl.py
store/bilibili/bilibili_store_sql.py

新增B站创作者（UP主）信息爬取（合并为单个commit）

---

media_platform/xhs/core.py

小红书查询没有结果时跳出循环

---

store/xhs/xhs_store_impl.py

fix: json内容保存格式优化，支持缩进

---

config/base_config.py
media_platform/xhs/client.py
media_platform/xhs/core.py

目前只进行了xhs的评论个数限制的更新，今后两天会需要增加对于其他平台的更新，以及增添产出数据的键名"current_note_comment_rank"

xiaohongshu_comment_number_restrict

---

store/xhs/__init__.py

xhs的性别为空的时候，存储为空
不知道有没有改变作者原本的意图

fix xhs gender

---

config/base_config.py
media_platform/bilibili/client.py
media_platform/bilibili/core.py
requirements.txt

---
此处添加了`START_DAY`与`END_DAY`以及`ALL_DAY`选项，在`ALL_DAY`为False时，使用原先关键词搜索策略，与原先版本保持不变；`ALL_DAY`为True时，从`START_DAY`与`END_DAY`中解析`client.py`中的`search_video_by_keyword`函数接收的`pubtime_begin_s`和`pubtime_end_s`参数，以实现最高支持细分为 1 天的视频记录，具体更改见之后提交的`client.py`和`core.py`。
Update core.py，以实现按照`START_DAY`至`END_DAY`，每一天进行筛选，这样能够突破 1000 条视频的限制，最大程度爬取该关键词下的所有视频。
添加了`get_pubtime_datetime`函数用以获取`pubtime_begin_s`和`pubtime_end_s`参数，并为`search`函数添加了`ALL_DAY`选项，若`ALL_DAY`未开启，则保留原先的搜索策略，但每个关键词最多返回 1000 条数据，若`ALL_DAY`已开启，则使用新策略，按照 `START_DAY `至 `END_DAY `按照每一天进行筛选，这样能够突破 1000 条视频的限制，最大程度爬取该关键词下的所有视频，新添加的`get_pubtime_datetime`函数仅在`search`中使用，需要用户按安装`datetime`和`pandas`模块。
Update client.py，将`search_video_by_keyword`中`post_data`错误的请求参数进行更新
`pubtime_begin`更改为`pubtime_begin_s`，`pubtime_end`更改为`pubtime_end_s`。
- 在KEYWORDS = …

为`base_config.py`添加了是否开启按每一天进行爬取的选项，仅支持bilibiili，Update `core.py`和`client.py`以实现该功能

---

media_platform/bilibili/core.py
media_platform/douyin/core.py
media_platform/xhs/client.py
media_platform/zhihu/help.py

zhihu某些情况，包括用户被封禁会报错终止进程。
bilibili我也不会修，但只要try包起来就能继续跑了。

避免预料之外的数据为None的情况终止进程

---

config/base_config.py
config/db_config.py
media_platform/bilibili/client.py
media_platform/bilibili/core.py
schema/tables.sql
store/bilibili/__init__.py
store/bilibili/bilibili_store_impl.py
store/bilibili/bilibili_store_sql.py
store/douyin/douyin_store_impl.py
store/kuaishou/kuaishou_store_impl.py
store/tieba/tieba_store_impl.py
store/weibo/weibo_store_impl.py
store/xhs/xhs_store_impl.py
store/zhihu/zhihu_store_impl.py

- :white_check_mark:  解决bilibili段爬取up主关系列表以及动态
- 具体拓展描述（示例）：
- 可根据用户所给creator_id爬取其粉丝和关注的具体列表
- 可根据用户所给creator_id爬取该up主所有动态
- 同原作者一样实现了csv，json，db三种存储方式
---
| 参数名       | 类型    | 默认值 | 说明                          |
|--------------|---------|--------|-------------------------------|
| `CREATOR_MODE`  | bool     | False      | 爬取作者视频评论 or 爬取动态粉丝列表           |
| `START_CONTACTS_PAGE` | int    | 1  | 爬取粉丝列表时起始页           |
| `CRAWLER_MAX_CONTACTS_COUNT_SINGLENOTES` | int    | 100  | 单个up主爬取粉丝(关注者)列表最大数量           |
| `CRAWLER_MAX_DYNAMICS_COUNT_SINGLENOTES` | int    | 50  | 单个up主爬取动态最大数量           |
---
🍉  对于拉取粉丝及关注者列表的方法，同拉取评论的方法类似。
🍋  对于拉取动态，发现下一页要传入的参数就是上一页结果中的offset，从而实现。
🍐  对于csv，json存储直接调用了原作者所写好的api
🍎  对于db存储，添加了2个表结构，并仿造原作者写好相应的方法
🥭  **顺便解决了db表初始化由于zhihu的表未drop而初始化失败的问题**
--- …

Bili_function_expand

---

media_platform/xhs/client.py

爬取小红书作者帖子时CRAWLER_MAX_NOTES_COUNT并未起作用，导致一直爬取并超量，故请求修复

修复CRAWLER_MAX_NOTES_COUNT在爬取小红书作者帖子时失效的问题

---

README.md
README_en.md
README_es.md

This PR adds comprehensive multilingual documentation support to MediaCrawler, making the project accessible to the international developer community. The changes include complete English and Spanish translations of the README with intuitive language navigation.
- **`README_en.md`** - Complete English translation
- **`README_es.md`** - Complete Spanish translation  
- **Enhanced `README.md`** - Original Chinese with navigation links
- **Prominent language selector** at the top of each README
- **Flag emojis** (🇨🇳 🇺🇸 🇪🇸) for visual clarity
- **Current language indicator** with arrow (← Current/当前/Actual)
- **Relative links** that work on both GitHub and local repositories
- **Consistent design** across all three language versions
- **100% accurate translations** - No content omitted, …

🌐 Add multilingual documentation support (English & Spanish)

---

pyproject.toml
requirements.txt
uv.lock

Update playwright version to support Ubuntu 24.04

---

media_platform/douyin/client.py

修复dy二级评论，无法获取用户定位问题。
获取子评论增加item_id（aweme_id）字段。

feat: 修复抖音二级评论地理位置缺失问题

---

requirements.txt

add aiosqlite==0.21.0 for requirements.txt

add aiosqlite

---

media_platform/bilibili/core.py
media_platform/douyin/core.py
media_platform/kuaishou/core.py
media_platform/tieba/core.py
media_platform/weibo/core.py
media_platform/xhs/core.py
media_platform/zhihu/core.py
tools/crawler_util.py

统一一下代理解析工具函数调用方式，后续更新代理解析格式只需要改动一个地方。

refactor: move format_proxy_info to utils and update crawler classes
